package com.tiger.employees.balanceitem.po;

// Generated Jan 27, 2015 11:20:51 AM by Hibernate Tools 3.4.0.CR1

/**
 * BalanceItem generated by hbm2java
 */
public class BalanceItem implements java.io.Serializable {

	private String id;
	private String balanceType;
	private String itemName;
	private String relatedCode;
	private String ifFomula;
	private String fomula;
	private String comment;
	private String itemType;
	private String itemNo;

	public BalanceItem() {
	}

	public BalanceItem(String id) {
		this.id = id;
	}

	public BalanceItem(String id, String balanceType, String itemName,
			String relatedCode, String ifFomula, String fomula, String comment,
			String itemType, String itemNo) {
		this.id = id;
		this.balanceType = balanceType;
		this.itemName = itemName;
		this.relatedCode = relatedCode;
		this.ifFomula = ifFomula;
		this.fomula = fomula;
		this.comment = comment;
		this.itemType = itemType;
		this.itemNo = itemNo;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBalanceType() {
		return this.balanceType;
	}

	public void setBalanceType(String balanceType) {
		this.balanceType = balanceType;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getRelatedCode() {
		return this.relatedCode;
	}

	public void setRelatedCode(String relatedCode) {
		this.relatedCode = relatedCode;
	}

	public String getIfFomula() {
		return this.ifFomula;
	}

	public void setIfFomula(String ifFomula) {
		this.ifFomula = ifFomula;
	}

	public String getFomula() {
		return this.fomula;
	}

	public void setFomula(String fomula) {
		this.fomula = fomula;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

}
