package com.tiger.employees.voucherdetail.po;

// Generated Oct 29, 2014 5:18:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * VoucherDetail generated by hbm2java
 */
public class VoucherDetail implements java.io.Serializable {

	private String id;
	private String orgId;
	private String voucherId;
	private String subjectId;
	private BigDecimal debit;
	private BigDecimal credit;
	private String settleTime;
	private String updateTime;
	private String comment;
	private String subjectRootCode;
	private String settleWay;//结算方式

	public VoucherDetail() {
	}

	public VoucherDetail(String id) {
		this.id = id;
	}

	public VoucherDetail(String id, String orgId, String voucherId,
			String subjectId, BigDecimal debit, BigDecimal credit,
			String settleTime, String updateTime, String comment,String subjectRootCode) {
		this.id = id;
		this.orgId = orgId;
		this.voucherId = voucherId;
		this.subjectId = subjectId;
		this.debit = debit;
		this.credit = credit;
		this.settleTime = settleTime;
		this.updateTime = updateTime;
		this.comment = comment;
		this.subjectRootCode=subjectRootCode;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getVoucherId() {
		return this.voucherId;
	}

	public void setVoucherId(String voucherId) {
		this.voucherId = voucherId;
	}

	public String getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}

	public BigDecimal getDebit() {
		return this.debit;
	}

	public void setDebit(BigDecimal debit) {
		this.debit = debit;
	}

	public BigDecimal getCredit() {
		return this.credit;
	}

	public void setCredit(BigDecimal credit) {
		this.credit = credit;
	}

	public String getSettleTime() {
		return this.settleTime;
	}

	public void setSettleTime(String settleTime) {
		this.settleTime = settleTime;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the subjectRootCode
	 */
	public String getSubjectRootCode() {
		return subjectRootCode;
	}

	/**
	 * @param subjectRootCode the subjectRootCode to set
	 */
	public void setSubjectRootCode(String subjectRootCode) {
		this.subjectRootCode = subjectRootCode;
	}

	/**
	 * @return the settleWay
	 */
	public String getSettleWay() {
		return settleWay;
	}

	/**
	 * @param settleWay the settleWay to set
	 */
	public void setSettleWay(String settleWay) {
		this.settleWay = settleWay;
	}

}
