package com.tiger.employees.monsettleprog.po;

// Generated Oct 25, 2014 7:37:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * MonthSettleProgress generated by hbm2java
 */
public class MonthSettleProgress implements java.io.Serializable {

	private String id;
	private String settleYear;
	private String settleMonth;
	private String status;
	private String createTime;
	private String updateTime;
	private String comment;
	private String companyId;

	public MonthSettleProgress() {
	}

	public MonthSettleProgress(String id) {
		this.id = id;
	}

	public MonthSettleProgress(String id, String settleYear,
			String settleMonth, String status, String createTime,
			String updateTime, String comment, String companyId) {
		this.id = id;
		this.settleYear = settleYear;
		this.settleMonth = settleMonth;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.comment = comment;
		this.companyId = companyId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSettleYear() {
		return this.settleYear;
	}

	public void setSettleYear(String settleYear) {
		this.settleYear = settleYear;
	}

	public String getSettleMonth() {
		return this.settleMonth;
	}

	public void setSettleMonth(String settleMonth) {
		this.settleMonth = settleMonth;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

}
