package com.tiger.employees.subject.po;

// Generated Aug 21, 2014 2:42:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	private String id;
	private String code;
	private String parentCode;
	private String parentId;
	private String childLv1;
	private String childLv2;
	private String childLv3;
	private String childLv4;
	private String childLv5;
	private String isLeaf;
	private String status;
	private Date createTime;
	private Date updateTime;
	private String comment;
	private String orgId;
	private Integer accountDirection;

	public Subject() {
	}

	public Subject(String id) {
		this.id = id;
	}

	public Subject(String id, String code, String parentCode, String parentId,
			String childLv1, String childLv2, String childLv3, String childLv4,
			String childLv5, String isLeaf, String status, Date createTime,
			Date updateTime, String comment,Integer accountDirection) {
		this.id = id;
		this.code = code;
		this.parentCode = parentCode;
		this.parentId = parentId;
		this.childLv1 = childLv1;
		this.childLv2 = childLv2;
		this.childLv3 = childLv3;
		this.childLv4 = childLv4;
		this.childLv5 = childLv5;
		this.isLeaf = isLeaf;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.comment = comment;
		this.accountDirection= accountDirection;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getChildLv1() {
		return this.childLv1;
	}

	public void setChildLv1(String childLv1) {
		this.childLv1 = childLv1;
	}

	public String getChildLv2() {
		return this.childLv2;
	}

	public void setChildLv2(String childLv2) {
		this.childLv2 = childLv2;
	}

	public String getChildLv3() {
		return this.childLv3;
	}

	public void setChildLv3(String childLv3) {
		this.childLv3 = childLv3;
	}

	public String getChildLv4() {
		return this.childLv4;
	}

	public void setChildLv4(String childLv4) {
		this.childLv4 = childLv4;
	}

	public String getChildLv5() {
		return this.childLv5;
	}

	public void setChildLv5(String childLv5) {
		this.childLv5 = childLv5;
	}

	public String getIsLeaf() {
		return this.isLeaf;
	}

	public void setIsLeaf(String isLeaf) {
		this.isLeaf = isLeaf;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the orgId
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * @param orgId the orgId to set
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	/**
	 * @return the accountDirection
	 */
	public Integer getAccountDirection() {
		return accountDirection;
	}

	/**
	 * @param accountDirection the accountDirection to set
	 */
	public void setAccountDirection(Integer accountDirection) {
		this.accountDirection = accountDirection;
	}
}
