package com.tiger.employees.compsettleprog.po;

// Generated Sep 28, 2014 5:17:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompanySettleProgress generated by hbm2java
 */
public class CompanySettleProgress implements java.io.Serializable {

	private String id;
	private String companyId;
	private String status;
	private String createTime;
	private String comment;

	public CompanySettleProgress() {
	}

	public CompanySettleProgress(String id) {
		this.id = id;
	}

	public CompanySettleProgress(String id, String companyId, String status,
			String createTime, String comment) {
		this.id = id;
		this.companyId = companyId;
		this.status = status;
		this.createTime = createTime;
		this.comment = comment;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
