package com.tiger.employees.settledetail.po;

// Generated Aug 23, 2014 10:17:40 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SettleDetail generated by hbm2java
 */
public class SettleDetail implements java.io.Serializable {

	private String id;
	private String orgId;
	private String settleId;
	private String subjectId;
	private BigDecimal debit;
	private BigDecimal credit;
	private String settleTime;
	private String updateTime;
	private String comment;

	public SettleDetail() {
	}

	public SettleDetail(String id) {
		this.id = id;
	}

	public SettleDetail(String id, String orgId, String settleId,
			String subjectId, BigDecimal debit, BigDecimal credit,
			String settleTime, String updateTime, String comment) {
		this.id = id;
		this.orgId = orgId;
		this.settleId = settleId;
		this.subjectId = subjectId;
		this.debit = debit;
		this.credit = credit;
		this.settleTime = settleTime;
		this.updateTime = updateTime;
		this.comment = comment;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getSettleId() {
		return this.settleId;
	}

	public void setSettleId(String settleId) {
		this.settleId = settleId;
	}

	public String getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}

	public BigDecimal getDebit() {
		return this.debit;
	}

	public void setDebit(BigDecimal debit) {
		this.debit = debit;
	}

	public BigDecimal getCredit() {
		return this.credit;
	}

	public void setCredit(BigDecimal credit) {
		this.credit = credit;
	}

	public String getSettleTime() {
		return this.settleTime;
	}

	public void setSettleTime(String settleTime) {
		this.settleTime = settleTime;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
