package com.tiger.employees.voucher.po;

// Generated Oct 29, 2014 4:58:45 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Voucher generated by hbm2java
 */
public class Voucher implements java.io.Serializable {

	private String id;
	private String orgId;
	private String voucherNo;
	private String subjectId;
	private BigDecimal debitSum;
	private BigDecimal creditSum;
	private BigDecimal diff;
	private String debitSubjectCodes;
	private String creditSubjectCodes;
	private String settleTime;
	private String updateTime;
	private String comment;

	public Voucher() {
	}

	public Voucher(String id) {
		this.id = id;
	}

	public Voucher(String id, String orgId, String voucherNo, String subjectId,
			BigDecimal debitSum, BigDecimal creditSum, BigDecimal diff,
			String debitSubjectCodes, String creditSubjectCodes,
			String settleTime, String updateTime, String comment) {
		this.id = id;
		this.orgId = orgId;
		this.voucherNo = voucherNo;
		this.subjectId = subjectId;
		this.debitSum = debitSum;
		this.creditSum = creditSum;
		this.diff = diff;
		this.debitSubjectCodes = debitSubjectCodes;
		this.creditSubjectCodes = creditSubjectCodes;
		this.settleTime = settleTime;
		this.updateTime = updateTime;
		this.comment = comment;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	public String getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}

	public BigDecimal getDebitSum() {
		return this.debitSum;
	}

	public void setDebitSum(BigDecimal debitSum) {
		this.debitSum = debitSum;
	}

	public BigDecimal getCreditSum() {
		return this.creditSum;
	}

	public void setCreditSum(BigDecimal creditSum) {
		this.creditSum = creditSum;
	}

	public BigDecimal getDiff() {
		return this.diff;
	}

	public void setDiff(BigDecimal diff) {
		this.diff = diff;
	}

	public String getDebitSubjectCodes() {
		return this.debitSubjectCodes;
	}

	public void setDebitSubjectCodes(String debitSubjectCodes) {
		this.debitSubjectCodes = debitSubjectCodes;
	}

	public String getCreditSubjectCodes() {
		return this.creditSubjectCodes;
	}

	public void setCreditSubjectCodes(String creditSubjectCodes) {
		this.creditSubjectCodes = creditSubjectCodes;
	}

	public String getSettleTime() {
		return this.settleTime;
	}

	public void setSettleTime(String settleTime) {
		this.settleTime = settleTime;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
